blank_issues_enabled: false
contact_links:
  - name: Installation help
    url: https://github.com/scoppy9201/OmmicomMail/discussions
    about: If you have questions about running OmmicomMail on your servers, use GitHub Discussions.

  - name: Help with using OmmicomMail
    url: https://github.com/scoppy9201/OmmicomMail/discussions
    about: If you need help using OmmicomMail's features, use GitHub Discussions.

  - name: Feature Suggestions
    url: https://github.com/scoppy9201/OmmicomMail/discussions
    about: Suggest a new feature that should be added to OmmicomMail.
