# This is an example OmmicomMail configuration file for use in
# development environments. For a production example, see
# this repository's deployment documentation.

version: 2

postal:
  web_hostname: ommicommail.example.com
  web_protocol: https
  smtp_hostname: smtp.ommicommail.example.com

main_db:
  host: 127.0.0.1
  username: root
  password: 
  database: postal

message_db:
  host: 127.0.0.1
  username: root
  password: 
  prefix: postal

logging:
  rails_log_enabled: true
  highlighting_enabled: true

rails:
  environment: development
  secret_key: 7f27856d26e864bafd49d0df37ad3d1339086e86ef0447e0f1814dde5277452fea97dab9e3aad6dfa11bfe359c82ce302d97bf1e58f6103c4408e4fbad4eeccf
